version: '3.7'

services:
  db:
    image: mysql:5.7
    tmpfs: /var/lib/mysql:rw
    command: [
      'mysqld',
      '--innodb-buffer-pool-size=20M',
      '--character-set-server=utf8mb4',
      '--default-time-zone=+8:00',
      '--lower-case-table-names=1',
      '--max-connections=1000',
      '--sql_mode=STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
    ]
    environment:
      - "MYSQL_DATABASE=game"
      - "MYSQL_ALLOW_EMPTY_PASSWORD=true"
      - "MYSQL_ROOT_PASSWORD="
    ports:
      - "3306:3306"
